# Name is optional and if present must be used
# in the url path for badges
name: Deploy Dev CDN

# Run on a dev branch
on: 
  push:
    branches:
    - master

jobs:
  Build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.15.1]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      # npm ci REQUIRES a package-lock.json file
      - name: Install Fresh Dependencies
        run: |
          rm package-lock.json
          npm install
      - name: Build library
        run: npm run build
      - name: Log build output
        run: ls -alt dist/
      - name: Archive Artifact (Build)
        uses: actions/upload-artifact@v1
        with:
          name: build
          path: dist/

  push-to-cdn:
    name: Push to CDN
    needs: build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.15]

    steps:
      - name: Checkout CDN Repository
        uses: actions/checkout@v2
        with:
          repository: zingsoftinc/zingchart-cdn
          ref: refs/heads/dev
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      - name: Download Build Artifacts
        uses: actions/download-artifact@v1
        with:
          name: build
      - name: Move Build to React Folder
        run: |
          cp -a build/ public/react/
      - name: Commit files
        run: |
          git add public/react/
          git config --local user.email "admin@zingsoft.com"
          git config --local user.name "ZingSoft Admin"
          git commit -m "Pushing react build from https://github.com/zingsoftinc/zingchart-lib/commit/${{ github.sha }}"
          git push https://zingsoftadmin:${{ secrets.PERSONAL_ACCESS_TOKEN }}@github.com/zingsoftinc/zingchart-cdn.git